"""add timeline fields to projects

Revision ID: 1835dfba690c
Revises: 512672878fbe
Create Date: 2025-11-12 16:28:49.224837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1835dfba690c'
down_revision = '512672878fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('timeline', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('text_bin_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'text_bin_items')
    op.drop_column('projects', 'timeline')
    # ### end Alembic commands ###

