"""init schema

Revision ID: 512672878fbe
Revises: 
Create Date: 2025-11-12 15:31:34.951126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512672878fbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

